apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ubuntu
spec:
  serviceName: "ubuntu"
  replicas: 5
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: abhaydandgedocker/ubuntu-ssh
          ports:
            - containerPort: 22
          volumeMounts:
            - name: data
              mountPath: /data
      volumes: []
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
